const campsData = [
  {
    name: 'Cardiology Health & Vitality Camp',
    location: 'Central Community Hospital, NY',
    fees: 50,
    dateTime: '2026-09-15 09:00 AM',
    healthcareProfessional: 'Dr. Robert Chen (Cardiologist)',
    description:
      'Comprehensive cardiovascular screening, blood pressure monitoring, and heart wellness advice.',
    image: 'https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?w=600',
    organizerEmail: 'organizer@carecamp.com',
    participantCount: 4,
  },
  {
    name: 'Vision & Eye Care Wellness Camp',
    location: 'Community Center, Los Angeles, CA',
    fees: 0,
    dateTime: '2026-09-20 10:00 AM',
    healthcareProfessional: 'Dr. Emily Vance (Ophthalmologist)',
    description:
      'Free vision testing, glaucoma screening, and prescription consultations for all ages.',
    image: 'https://images.unsplash.com/photo-1584515979956-d9f6e5d09982?w=600',
    organizerEmail: 'organizer@carecamp.com',
    participantCount: 3,
  },
  {
    name: 'Pediatric Health Checkup & Vaccination',
    location: 'St. Jude Children Wing, Chicago, IL',
    fees: 25,
    dateTime: '2026-09-25 08:30 AM',
    healthcareProfessional: 'Dr. Maria Rodriguez (Pediatrician)',
    description: 'Growth monitoring, seasonal flu vaccinations, and child nutrition guidance.',
    image: 'https://images.unsplash.com/photo-1581594693702-fbdc51b2763b?w=600',
    organizerEmail: 'organizer@carecamp.com',
    participantCount: 2,
  },
  {
    name: 'Dental Care & Smile Restoration Camp',
    location: 'Downtown Dental Clinic, Houston, TX',
    fees: 30,
    dateTime: '2026-10-01 09:00 AM',
    healthcareProfessional: 'Dr. Alan Harper (DDS)',
    description:
      'Teeth cleaning, cavity checks, oral hygiene workshops, and free dental hygiene kits.',
    image: 'https://images.unsplash.com/photo-1606811841689-23dfddce3e95?w=600',
    organizerEmail: 'admin@carecamp.com',
    participantCount: 1,
  },
  {
    name: 'Orthopedic & Joint Health Camp',
    location: 'Sports Rehab Facility, Phoenix, AZ',
    fees: 40,
    dateTime: '2026-10-05 11:00 AM',
    healthcareProfessional: 'Dr. James Thorne (Orthopedic Specialist)',
    description:
      'Bone density assessments, joint mobility tests, and arthritis care consultations.',
    image: 'https://images.unsplash.com/photo-1579684385127-1ef15d508118?w=600',
    organizerEmail: 'admin@carecamp.com',
    participantCount: 0,
  },
  {
    name: 'Diabetes & Endocrine Health Awareness',
    location: 'Metabolic Care Center, Philadelphia, PA',
    fees: 15,
    dateTime: '2026-10-10 09:30 AM',
    healthcareProfessional: 'Dr. Priya Sharma (Endocrinologist)',
    description: 'HbA1c testing, blood glucose checks, and personalized diabetic diet plans.',
    image: 'https://images.unsplash.com/photo-1505751172876-fa1923c5c528?w=600',
    organizerEmail: 'organizer@carecamp.com',
    participantCount: 0,
  },
  {
    name: 'Dermatology & Skin Care Wellness Camp',
    location: 'Skin Institute, San Antonio, TX',
    fees: 35,
    dateTime: '2026-10-15 10:00 AM',
    healthcareProfessional: 'Dr. Sophia Martinez (Dermatologist)',
    description: 'Skin cancer screening, eczema management, and sun protection counseling.',
    image: 'https://images.unsplash.com/photo-1629909613654-28e377c37b09?w=600',
    organizerEmail: 'admin@carecamp.com',
    participantCount: 0,
  },
  {
    name: 'ENT & Hearing Care Camp',
    location: 'Audiology Center, San Diego, CA',
    fees: 20,
    dateTime: '2026-10-20 09:00 AM',
    healthcareProfessional: 'Dr. William Blake (ENT Specialist)',
    description: 'Hearing evaluations, ear wax removal, and sinus consultations.',
    image: 'https://images.unsplash.com/photo-1516549655169-df83a0774514?w=600',
    organizerEmail: 'organizer@carecamp.com',
    participantCount: 0,
  },
  {
    name: 'Neurology & Memory Wellness Checkup',
    location: 'Brain & Spine Institute, Boston, MA',
    fees: 60,
    dateTime: '2026-10-25 01:00 PM',
    healthcareProfessional: 'Dr. Arthur Pendelton (Neurologist)',
    description: 'Cognitive assessments, stroke prevention screening, and reflex testing.',
    image: 'https://images.unsplash.com/photo-1551076805-e1869033e561?w=600',
    organizerEmail: 'admin@carecamp.com',
    participantCount: 0,
  },
  {
    name: 'Women Medical Wellness & Gynecological Camp',
    location: 'Grace Women Hospital, Dallas, TX',
    fees: 0,
    dateTime: '2026-11-01 09:00 AM',
    healthcareProfessional: 'Dr. Rebecca Foster (OB/GYN)',
    description:
      'Free cervical screening, mammogram consultations, and maternal wellness workshops.',
    image: 'https://images.unsplash.com/photo-1532938911079-1b06ac7ceec7?w=600',
    organizerEmail: 'organizer@carecamp.com',
    participantCount: 0,
  },
];

module.exports = { campsData };
