function getPaymentsSeedData(seededCamps, seededRegistrations, participantsList) {
  return [
    {
      campId: seededCamps[0]._id,
      registrationId: seededRegistrations[0]._id,
      participantEmail: participantsList[0].email,
      transactionId: 'txn_1001',
      amount: 50,
      paymentMethod: 'Stripe',
      paymentDate: new Date('2026-08-01'),
      status: 'Completed',
    },
    {
      campId: seededCamps[0]._id,
      registrationId: seededRegistrations[1]._id,
      participantEmail: participantsList[1].email,
      transactionId: 'txn_1002',
      amount: 50,
      paymentMethod: 'Stripe',
      paymentDate: new Date('2026-08-02'),
      status: 'Completed',
    },
    {
      campId: seededCamps[0]._id,
      registrationId: seededRegistrations[2]._id,
      participantEmail: participantsList[2].email,
      transactionId: 'txn_1003',
      amount: 50,
      paymentMethod: 'Stripe',
      paymentDate: new Date('2026-08-03'),
      status: 'Completed',
    },
    {
      campId: seededCamps[1]._id,
      registrationId: seededRegistrations[4]._id,
      participantEmail: participantsList[0].email,
      transactionId: 'txn_1005',
      amount: 0,
      paymentMethod: 'Stripe',
      paymentDate: new Date('2026-08-05'),
      status: 'Completed',
    },
    {
      campId: seededCamps[1]._id,
      registrationId: seededRegistrations[5]._id,
      participantEmail: participantsList[4].email,
      transactionId: 'txn_1006',
      amount: 0,
      paymentMethod: 'Stripe',
      paymentDate: new Date('2026-08-06'),
      status: 'Completed',
    },
    {
      campId: seededCamps[2]._id,
      registrationId: seededRegistrations[7]._id,
      participantEmail: participantsList[6].email,
      transactionId: 'txn_1008',
      amount: 25,
      paymentMethod: 'Stripe',
      paymentDate: new Date('2026-08-08'),
      status: 'Completed',
    },
    {
      campId: seededCamps[2]._id,
      registrationId: seededRegistrations[8]._id,
      participantEmail: participantsList[7].email,
      transactionId: 'txn_1009',
      amount: 25,
      paymentMethod: 'Stripe',
      paymentDate: new Date('2026-08-09'),
      status: 'Completed',
    },
    {
      campId: seededCamps[3]._id,
      registrationId: seededRegistrations[9]._id,
      participantEmail: participantsList[0].email,
      transactionId: 'txn_1010',
      amount: 30,
      paymentMethod: 'Stripe',
      paymentDate: new Date('2026-08-10'),
      status: 'Completed',
    },
    {
      campId: seededCamps[4]._id,
      registrationId: seededRegistrations[3]._id,
      participantEmail: participantsList[3].email,
      transactionId: 'txn_1011_pending',
      amount: 40,
      paymentMethod: 'Stripe',
      paymentDate: new Date('2026-08-11'),
      status: 'Pending',
    },
    {
      campId: seededCamps[5]._id,
      registrationId: seededRegistrations[6]._id,
      participantEmail: participantsList[5].email,
      transactionId: 'txn_1012_pending',
      amount: 15,
      paymentMethod: 'Stripe',
      paymentDate: new Date('2026-08-11'),
      status: 'Pending',
    },
  ];
}

module.exports = { getPaymentsSeedData };
