function getRegistrationsSeedData(seededCamps, participantsList) {
  return [
    {
      campId: seededCamps[0]._id,
      participantEmail: participantsList[0].email,
      participantName: participantsList[0].name,
      age: 34,
      phoneNumber: '+1 555-0144',
      gender: 'Male',
      emergencyContact: '+1 555-9999',
      registrationDate: new Date('2026-08-01'),
      paymentStatus: 'Paid',
      confirmationStatus: 'Confirmed',
      transactionId: 'txn_1001',
    },
    {
      campId: seededCamps[0]._id,
      participantEmail: participantsList[1].email,
      participantName: participantsList[1].name,
      age: 29,
      phoneNumber: '+1 555-0155',
      gender: 'Female',
      emergencyContact: '+1 555-8888',
      registrationDate: new Date('2026-08-02'),
      paymentStatus: 'Paid',
      confirmationStatus: 'Confirmed',
      transactionId: 'txn_1002',
    },
    {
      campId: seededCamps[0]._id,
      participantEmail: participantsList[2].email,
      participantName: participantsList[2].name,
      age: 45,
      phoneNumber: '+1 555-0166',
      gender: 'Male',
      emergencyContact: '+1 555-7777',
      registrationDate: new Date('2026-08-03'),
      paymentStatus: 'Paid',
      confirmationStatus: 'Confirmed',
      transactionId: 'txn_1003',
    },
    {
      campId: seededCamps[0]._id,
      participantEmail: participantsList[3].email,
      participantName: participantsList[3].name,
      age: 38,
      phoneNumber: '+1 555-0177',
      gender: 'Female',
      emergencyContact: '+1 555-6666',
      registrationDate: new Date('2026-08-04'),
      paymentStatus: 'Unpaid',
      confirmationStatus: 'Pending',
      transactionId: 'txn_1004_unpaid',
    },
    {
      campId: seededCamps[1]._id,
      participantEmail: participantsList[0].email,
      participantName: participantsList[0].name,
      age: 34,
      phoneNumber: '+1 555-0144',
      gender: 'Male',
      emergencyContact: '+1 555-9999',
      registrationDate: new Date('2026-08-05'),
      paymentStatus: 'Paid',
      confirmationStatus: 'Confirmed',
      transactionId: 'txn_1005',
    },
    {
      campId: seededCamps[1]._id,
      participantEmail: participantsList[4].email,
      participantName: participantsList[4].name,
      age: 52,
      phoneNumber: '+1 555-0188',
      gender: 'Male',
      emergencyContact: '+1 555-5555',
      registrationDate: new Date('2026-08-06'),
      paymentStatus: 'Paid',
      confirmationStatus: 'Confirmed',
      transactionId: 'txn_1006',
    },
    {
      campId: seededCamps[1]._id,
      participantEmail: participantsList[5].email,
      participantName: participantsList[5].name,
      age: 27,
      phoneNumber: '+1 555-0190',
      gender: 'Female',
      emergencyContact: '+1 555-4444',
      registrationDate: new Date('2026-08-07'),
      paymentStatus: 'Unpaid',
      confirmationStatus: 'Pending',
      transactionId: 'txn_1007_unpaid',
    },
    {
      campId: seededCamps[2]._id,
      participantEmail: participantsList[6].email,
      participantName: participantsList[6].name,
      age: 41,
      phoneNumber: '+1 555-0191',
      gender: 'Male',
      emergencyContact: '+1 555-3333',
      registrationDate: new Date('2026-08-08'),
      paymentStatus: 'Paid',
      confirmationStatus: 'Confirmed',
      transactionId: 'txn_1008',
    },
    {
      campId: seededCamps[2]._id,
      participantEmail: participantsList[7].email,
      participantName: participantsList[7].name,
      age: 31,
      phoneNumber: '+1 555-0192',
      gender: 'Female',
      emergencyContact: '+1 555-2222',
      registrationDate: new Date('2026-08-09'),
      paymentStatus: 'Paid',
      confirmationStatus: 'Confirmed',
      transactionId: 'txn_1009',
    },
    {
      campId: seededCamps[3]._id,
      participantEmail: participantsList[0].email,
      participantName: participantsList[0].name,
      age: 34,
      phoneNumber: '+1 555-0144',
      gender: 'Male',
      emergencyContact: '+1 555-9999',
      registrationDate: new Date('2026-08-10'),
      paymentStatus: 'Paid',
      confirmationStatus: 'Confirmed',
      transactionId: 'txn_1010',
    },
  ];
}

module.exports = { getRegistrationsSeedData };
