const bcrypt = require('bcryptjs');

async function getUsersSeedData() {
  const hashedPass = await bcrypt.hash('Password123!', 10);

  return [
    {
      email: 'organizer@carecamp.com',
      password: hashedPass,
      name: 'Dr. Sarah Connor',
      photoURL: 'https://images.unsplash.com/photo-1559839734-2b71ea197ec2?w=150',
      role: 'organizer',
      phone: '+1 555-0199',
      address: 'CareCamp HQ, Medical Tower, NY',
      created_at: new Date().toISOString(),
      last_login: new Date().toISOString(),
    },
    {
      email: 'admin@carecamp.com',
      password: hashedPass,
      name: 'Dr. Marcus Vance',
      photoURL: 'https://images.unsplash.com/photo-1622253692010-333f2da6031d?w=150',
      role: 'organizer',
      phone: '+1 555-0100',
      address: '100 Admin Plaza, Boston, MA',
      created_at: new Date().toISOString(),
      last_login: new Date().toISOString(),
    },
    {
      email: 'participant@carecamp.com',
      password: hashedPass,
      name: 'John Doe',
      photoURL: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150',
      role: 'participant',
      phone: '+1 555-0144',
      address: '123 Health Ave, Los Angeles, CA',
      created_at: new Date().toISOString(),
      last_login: new Date().toISOString(),
    },
    {
      email: 'sarah.smith@yahoo.com',
      password: hashedPass,
      name: 'Sarah Smith',
      photoURL: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150',
      role: 'participant',
      phone: '+1 555-0155',
      address: '456 Oak Street, Chicago, IL',
      created_at: new Date().toISOString(),
      last_login: new Date().toISOString(),
    },
    {
      email: 'michael.brown@outlook.com',
      password: hashedPass,
      name: 'Michael Brown',
      photoURL: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150',
      role: 'participant',
      phone: '+1 555-0166',
      address: '789 Pine Road, Houston, TX',
      created_at: new Date().toISOString(),
      last_login: new Date().toISOString(),
    },
    {
      email: 'emily.davis@health.org',
      password: hashedPass,
      name: 'Emily Davis',
      photoURL: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=150',
      role: 'participant',
      phone: '+1 555-0177',
      address: '321 Maple Ave, Phoenix, AZ',
      created_at: new Date().toISOString(),
      last_login: new Date().toISOString(),
    },
    {
      email: 'david.wilson@clinic.net',
      password: hashedPass,
      name: 'David Wilson',
      photoURL: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150',
      role: 'participant',
      phone: '+1 555-0188',
      address: '654 Elm Court, Philadelphia, PA',
      created_at: new Date().toISOString(),
      last_login: new Date().toISOString(),
    },
    {
      email: 'jessica.taylor@medical.com',
      password: hashedPass,
      name: 'Jessica Taylor',
      photoURL: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150',
      role: 'participant',
      phone: '+1 555-0190',
      address: '987 Cedar Blvd, San Antonio, TX',
      created_at: new Date().toISOString(),
      last_login: new Date().toISOString(),
    },
    {
      email: 'james.anderson@wellness.org',
      password: hashedPass,
      name: 'James Anderson',
      photoURL: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150',
      role: 'participant',
      phone: '+1 555-0191',
      address: '147 Spruce Lane, San Diego, CA',
      created_at: new Date().toISOString(),
      last_login: new Date().toISOString(),
    },
    {
      email: 'amanda.white@care.com',
      password: hashedPass,
      name: 'Amanda White',
      photoURL: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150',
      role: 'participant',
      phone: '+1 555-0192',
      address: '258 Birch St, Dallas, TX',
      created_at: new Date().toISOString(),
      last_login: new Date().toISOString(),
    },
  ];
}

module.exports = { getUsersSeedData };
